site_name: Oscleton SDK Documentation
site_description: Ableton Live companion SDK for Android

copyright: 'Copyright © 2018 Arthur Vimond'

theme: 
  name: 'material'
  language: en
  feature:
    tabs: true
  logo: "assets/images/icon-white.png"
  custom_dir: 'theme'

extra:
  version: 0.1
  social:
    - type: 'globe'
      link: 'http://arthurvimond.fr'
    - type: 'github'
      link: 'https://github.com/arthurvimond'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/arthurvimond'

nav:
  - Introduction: index.md
  - Getting started:
    - Prerequisite: getting-started/prerequisite.md
    - Android:
      - Project setup: getting-started/android/project-setup.md
      - Configuration: getting-started/android/configuration.md
      - Controller: getting-started/android/controller.md
      - Receiver: getting-started/android/receiver.md
    - iOS:
      - Project setup: getting-started/ios/project-setup.md
      - Configuration: getting-started/ios/configuration.md
      - Controller: getting-started/ios/controller.md
      - Receiver: getting-started/ios/receiver.md
    
    

  - Android API reference:
    - Package Index: reference/android/index.md
    - SDK:
      - Overview: reference/android/com.oscleton.sdk/index.md
      - OscletonSDK: reference/android/com.oscleton.sdk/-oscleton-s-d-k/index.md
      - Configuration: reference/android/com.oscleton.sdk/-configuration/index.md
      - Controller: reference/android/com.oscleton.sdk/-controller/index.md
      - Receiver: reference/android/com.oscleton.sdk/-receiver/index.md
      - ReactiveReceiver: reference/android/com.oscleton.sdk/-reactive-receiver/index.md
      - CallbackReceiver: reference/android/com.oscleton.sdk/-callback-receiver/index.md
    - Enums:
      - Overview: reference/android/com.oscleton.sdk.enums/index.md
#      - ClipState: reference/android/com.oscleton.sdk.enums/-clip-state/index.md
      - SDKResult: reference/android/com.oscleton.sdk.enums/-s-d-k-result/index.md
      - TrackType: reference/android/com.oscleton.sdk.enums/-track-type/index.md
    - Exceptions:
      - Overview: reference/android/com.oscleton.sdk.exceptions/index.md
      - OscletonSDKException: reference/android/com.oscleton.sdk.exceptions/-oscleton-s-d-k-exception/index.md
    - Listeners:
      - Overview: reference/android/com.oscleton.sdk.listeners/index.md
      - OnConnectionSuccessListener: reference/android/com.oscleton.sdk.listeners/-on-connection-success-listener/index.md
      - OnDeviceParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-device-parameter-change-listener/index.md
      - OnTempoChangeListener: reference/android/com.oscleton.sdk.listeners/-on-tempo-change-listener/index.md
    - Models:
      - Overview: reference/android/com.oscleton.sdk.models/index.md
#      - Clip: reference/android/com.oscleton.sdk.models/-clip/index.md
#      - ClipSlot: reference/android/com.oscleton.sdk.models/-clip-slot/index.md
      - Device: reference/android/com.oscleton.sdk.models/-device/index.md
      - DeviceParameter: reference/android/com.oscleton.sdk.models/-device-parameter/index.md
#      - Scene: reference/android/com.oscleton.sdk.models/-scene/index.md
      - Track: reference/android/com.oscleton.sdk.models/-track/index.md
    - Utils:
      - Overview: reference/android/com.oscleton.sdk.utils/index.md
      - Empty: reference/android/com.oscleton.sdk.utils/-empty/index.md
#      - FormatUtils: reference/android/com.oscleton.sdk.utils/-format-utils/index.md
#      - MathUtils: reference/android/com.oscleton.sdk.utils/-math-utils/index.md
      - NetworkUtils: reference/android/com.oscleton.sdk.utils/-network-utils/index.md

  - iOS API reference:
    - Overview: reference/ios/README.md
    - SDK:
      - OscletonSDK: reference/ios/classes/OscletonSDK.md
      - OSConfiguration: reference/ios/classes/OSConfiguration.md
      - OSController: reference/ios/classes/OSController.md
      - OSReceiver: reference/ios/classes/OSReceiver.md
      - OSReactiveReceiver: reference/ios/classes/OSReactiveReceiver.md
      - OSCallbackReceiver: reference/ios/classes/OSCallbackReceiver.md
    - Enums:
      - OSResult: reference/ios/enums/OSResult.md
      - OSTrackType: reference/ios/enums/OSTrackType.md
    - Models:
      - OSDevice: reference/ios/classes/OSDevice.md
      - OSDeviceParameter: reference/ios/classes/OSDeviceParameter.md
      - OSTrack: reference/ios/classes/OSTrack.md

  - More:
    - Changelog: more/changelog.md
    - Feedback and issues: more/feedback-and-issues.md
    - License: more/license.md

markdown_extensions:
  - codehilite:
      linenums: false
  - markdown_fenced_code_tabs:
      single_block_as_tab: false
      active_class: 'active'
      template: 'default'


extra_javascript:
  - js/tabhack.js

extra_css:
#  - 'css/general.css'
  - 'css/code-tabs.css'