site_name: Oscleton SDK Documentation
site_description: Ableton Live companion SDK for Android and iOS

copyright: 'Copyright © 2018-2021 Arthur Vimond'

theme: 
  name: 'material'
  language: en
  feature:
    tabs: true
  logo: "assets/images/icon-white.png"
  custom_dir: 'theme'

extra:
  version: 1.0
  social:
    - type: 'globe'
      link: 'https://arthurvimond.fr'
    - type: 'github'
      link: 'https://github.com/arthurvimond'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/arthurvimond'

nav:
  - Introduction: index.md
  - Getting started:
    - Prerequisite: getting-started/prerequisite.md
    - Android:
      - Android project setup: getting-started/android/project-setup.md
      - Configuration: getting-started/android/configuration.md
      - LiveSet: getting-started/android/liveset.md
      - Tracks: getting-started/android/tracks.md
      - Devices: getting-started/android/devices.md
      - Browser: getting-started/android/browser.md
      - Controller: getting-started/android/controller.md
      - Receiver: getting-started/android/receiver.md
    - iOS:
      - iOS project setup: getting-started/ios/project-setup.md
      - Configuration: getting-started/ios/configuration.md
      - Controller: getting-started/ios/controller.md
      - Receiver: getting-started/ios/receiver.md
    
  - Android API reference:
    - Package Index: reference/android/index.md
    - SDK:
      - Overview: reference/android/com.oscleton.sdk/index.md
      - OscletonSDK: reference/android/com.oscleton.sdk/-oscleton-s-d-k/index.md
      - Configuration: reference/android/com.oscleton.sdk/-configuration/index.md
      - Controller: reference/android/com.oscleton.sdk/-controller/index.md
      - Receiver: reference/android/com.oscleton.sdk/-receiver/index.md
      - ReactiveReceiver: reference/android/com.oscleton.sdk/-reactive-receiver/index.md
      - CallbackReceiver: reference/android/com.oscleton.sdk/-callback-receiver/index.md
    - Enums:
      - Overview: reference/android/com.oscleton.sdk.enums/index.md
      - AppTrack: reference/android/com.oscleton.sdk.enums/-app-track/index.md
      - AutomationState: reference/android/com.oscleton.sdk.enums/-automation-state/index.md
      - LiveParameter: reference/android/com.oscleton.sdk.enums/-live-parameter/index.md
      - SDKResult: reference/android/com.oscleton.sdk.enums/-s-d-k-result/index.md
      - SendState: reference/android/com.oscleton.sdk.enums/-send-state/index.md
      - SendType: reference/android/com.oscleton.sdk.enums/-send-type/index.md
      - TrackType: reference/android/com.oscleton.sdk.enums/-track-type/index.md
    - Exceptions:
      - Overview: reference/android/com.oscleton.sdk.exceptions/index.md
      - OscletonSDKException: reference/android/com.oscleton.sdk.exceptions/-oscleton-s-d-k-exception/index.md
    - Listeners:
      - Overview: reference/android/com.oscleton.sdk.listeners/index.md
      - OnComputerIPDiscoveryCancelListener: reference/android/com.oscleton.sdk.listeners/-on-computer-i-p-discovery-cancel-listener/index.md
      - OnComputerIPDiscoveryErrorListener: reference/android/com.oscleton.sdk.listeners/-on-computer-i-p-discovery-error-listener/index.md
      - OnComputerIPDiscoveryProgressListener: reference/android/com.oscleton.sdk.listeners/-on-computer-i-p-discovery-progress-listener/index.md
      - OnComputerIPDiscoveryStartListener: reference/android/com.oscleton.sdk.listeners/-on-computer-i-p-discovery-start-listener/index.md
      - OnComputerIPDiscoverySuccessListener: reference/android/com.oscleton.sdk.listeners/-on-computer-i-p-discovery-success-listener/index.md
      - OnConnectionErrorListener: reference/android/com.oscleton.sdk.listeners/-on-connection-error-listener/index.md
      - OnConnectionSuccessListener: reference/android/com.oscleton.sdk.listeners/-on-connection-success-listener/index.md
      - OnDeviceParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-device-parameter-change-listener/index.md
      - OnMasterDeviceParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-master-device-parameter-change-listener/index.md
      - OnMasterParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-master-parameter-change-listener/index.md
      - OnQuitListener: reference/android/com.oscleton.sdk.listeners/-on-quit-listener/index.md
      - OnReturnDeviceParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-return-device-parameter-change-listener/index.md
      - OnReturnParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-return-parameter-change-listener/index.md
      - OnStartListener: reference/android/com.oscleton.sdk.listeners/-on-start-listener/index.md
      - OnTempoChangeListener: reference/android/com.oscleton.sdk.listeners/-on-tempo-change-listener/index.md
      - OnTrackDeviceParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-track-device-parameter-change-listener/index.md
      - OnTrackParameterChangeListener: reference/android/com.oscleton.sdk.listeners/-on-track-parameter-change-listener/index.md
      - OnTrackSendChangeListener: reference/android/com.oscleton.sdk.listeners/-on-track-send-change-listener/index.md
    - Models:
      - Overview: reference/android/com.oscleton.sdk.models/index.md
      - Device: reference/android/com.oscleton.sdk.models/-device/index.md
      - DeviceParameter: reference/android/com.oscleton.sdk.models/-device-parameter/index.md
      - MasterParameter: reference/android/com.oscleton.sdk.models/-master-parameter/index.md
      - ReturnParameter: reference/android/com.oscleton.sdk.models/-return-parameter/index.md
      - Send: reference/android/com.oscleton.sdk.models/-send/index.md
      - TrackParameter: reference/android/com.oscleton.sdk.models/-track-parameter/index.md
    - Utils:
      - Overview: reference/android/com.oscleton.sdk.utils/index.md
      - Empty: reference/android/com.oscleton.sdk.utils/-empty/index.md
      - NetworkUtils: reference/android/com.oscleton.sdk.utils/-network-utils/index.md

  - iOS API reference:
    - Overview: reference/ios/README.md
    - SDK:
      - OscletonSDK: reference/ios/classes/OscletonSDK.md
      - OSConfiguration: reference/ios/classes/OSConfiguration.md
      - OSController: reference/ios/classes/OSController.md
      - OSReceiver: reference/ios/classes/OSReceiver.md
      - OSReactiveReceiver: reference/ios/classes/OSReactiveReceiver.md
      - OSCallbackReceiver: reference/ios/classes/OSCallbackReceiver.md
    - Enums:
      - OSResult: reference/ios/enums/OSResult.md
      - OSTrackType: reference/ios/enums/OSTrackType.md
    - Models:
      - OSDevice: reference/ios/classes/OSDevice.md
      - OSDeviceParameter: reference/ios/classes/OSDeviceParameter.md
      - OSTrack: reference/ios/classes/OSTrack.md

  - More:
    - Android Changelog: more/android-changelog.md
    - iOS Changelog: more/ios-changelog.md
    - Feedback and issues: more/feedback-and-issues.md
    - License: more/license.md

markdown_extensions:
  - codehilite:
      linenums: false
  - markdown_fenced_code_tabs:
      single_block_as_tab: false
      active_class: 'active'
      template: 'default'


extra_javascript:
  - js/tabhack.js

extra_css:
  - 'css/code-tabs.css'